### PR TITLE
Add all Months until 2019-10

### PR DESCRIPTION
**Pull request by PhilmacFLy**

### CODE REVIEW

**Comment by rralf** [comment]
Thanks, cool!

I remember that I had to convert a lot of data in the wiki in order to import these data. Did you experience similar issues?

How did you import the missing data? Do you have access to the webserver?

Please let me validate the import, then I'll get back to you.

**Comment by tbnobody** [comment]
I i See wrong formatted log entries I correct them immediatly. E.g. wrong aligned images or empty bullet points. 
A few days ago I also checked the images and moved them to the right namespace if required.

**Comment by PhilmacFLy** [comment]
Yes I did a lot of this by Hand.
I downloaded the log pages by using dokuwikis "do=export_raw" to get the txt file and then add the header.
The images I put by hand in the folder structure.

**Comment by rralf** [comment]
Wow, that's a lot of manual work...
Ok, let me check the difference to the automatic approach tonight if we missed something.
Thanks!

**Comment by rralf** [comment]
I'm missing my webserver login data... Let me shift that to the weekend. Thanks!

**Comment by rralf** [comment]
Ok, I found some unparseable kitchenlog entries. Will have to fix that first.

**Comment by rralf** [comment]
@tbnobody I find oftern pattern where we include images like:

`{{ kitchenlog:entry:2018:07:img_20180731_212513.jpg?400 |}}`

Is that correct wiki syntax? My parser says no, but it might be wrong. Shoudn't this be:

`{{ :kitchenlog:entry:2018:07:img_20180731_212513.jpg?400 |}}`

which includes a preceeding colon. Will fix all spots in the wiki for the moment.

**Comment by rralf** [comment]
So that issue is really odd... Those entries have already been imported once. They must have changed. Did you use any script to batch-convert all of those entries?

**Comment by rralf** [comment]
There are also inconsistencies like:
`
{{ kitchenlog:entry:2018:11:img_20181103_091812-collage.jpg?600 |}}
{{ :kitchenlog:entry:2018:11:20181104_bk_im_fernsehen.png?400 |}}
`

Will fix that.

**Comment by rralf** [comment]
Seems like everything is in place now. I updated my parser: https://github.com/Binary-Kitchen/klog/commit/3c7f18608da19f48422b122b85a393453aeb4294

And it looks like a bunch of entries back in 2018 changed their text. I'll integrate them first (https://github.com/Binary-Kitchen/kitchenlog/commit/e8fc9e23e78eb95cc85e2cf04fe091d4e26c24ed), and then try to find out the differences between that state and Phil's pull request.

**Comment by PhilmacFLy** [comment]
Any update on this? :)

**Comment by rralf** [comment]
Yep, automatic update works, all broken wiki entries have been amended. I still have to diff those results with your pull request.

**Comment by PhilmacFLy** [comment]
Did you have a chance to diff the results with my pull request?

**Comment by rralf** [comment]
Yep, did it right now. There were already too many updates that would have caused conflicts, and checksums of your pictures didn't match with the raw ones (don't ask me why).

I integrated all data up to 2019/12 with my automatic klog_convert script.

Thanks for the patience!

**Pull request closed without merging**
